mysite/arch_blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'arch_blog'
urlpatterns = [
    # ex /arch_blog/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex /arch_blog/4/
    url(r'^(?P<post_id>[0-9]+)/$', views.post, name='post'),
    # ex /arch_blog/4/comment/
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.comment, name='comment')
] 

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^arch_blog/', include('arch_blog.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name = 'results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote'),
]

mysite/arch_blog/models.py
import datetime

from django.db import models
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length = 256)
    body = models.TextField(max_length = 4096)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.title
    def wasPublishedRecently(self):
        return self.pub_date <= timezone.now() - datetime.timedelta(days=1)
    def hasTag(self, a_tag):
        return self.tag_set.filter(tag=a_tag).distinct().count() == 1
    def getTags(self):
        return self.tag_set.all()
    def getComments(self):
        return self.comment_set.all()
    def getAbstract(self):
        if len(self.body) < 150:
            return self.body + '...'
        else:
            return self.body[:150] + '...'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    body = models.TextField(max_length = 1024)
    author = models.CharField(max_length = 128)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.body

class Tag(models.Model):
    name = models.CharField(max_length=64)
    posts = models.ManyToManyField(Post)
    def __str__(self):
        return self.name
    

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/arch_blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Post, Comment


class IndexView(generic.ListView):
    template_name = 'arch_blog/index.html'
    context_object_name = 'latest_posts'

    def get_queryset(self):
        return Post.objects.order_by('-pub_date')[:5]
     
def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.getComments()
    tags = post.getTags()
    return render(request, 'arch_blog/post.html', {'post' : post, 'comments': comments, 'tags': tags,})

def comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    try:             
        if request.POST['body'] == '' or request.POST['author'] == '':
            HttpResponseRedirect(reverse('arch_blog:post', args=(post_id)))
        else:
            c = Comment()
            c.body = request.POST['body']
            c.author = request.POST['author']
            c.pub_date = timezone.now()
            c.post = post
            c.save()
    except:
        HttpResponseRedirect(reverse('arch_blog:index'))
    return HttpResponseRedirect(reverse('arch_blog:post', args=(post_id)))
    
        

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import F
from django.views import generic

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message': 'You did not select a choice',
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

mysite/arch_blog/templates/arch_blog/index.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'arch_blog/style.css' %}" />
        <link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet'>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="{% static 'arch_blog/app.js' %}"></script>
    </head>
    <body>
        <div class="header">
            <div class="positioning">
                <div class="container">
                    <a href="{% url 'arch_blog:index' %}"><img src="http://s3.amazonaws.com/codecademy-content/courses/ltp2/img/flipboard/logo.png"/></a>
                    <ul class="menu">
                        <li><a href="#">Item1</a></li>
                        <li><a href="#">Item2</a></li>
                        <li><a href="#">Item3</a></li>
                        <li><a href="#">Item4</a></li>
                        <li class="dropdown-toggle">
                            <a href="#">More</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">DropdownItem1</a></li>
                                <li><a href="#">DropdownItem2</a></li>
                                <li><a href="#">DropdownItem3</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="positioning">
            <div class="posts">
            {% if latest_posts %}
                <ul>
                {% for post in latest_posts %}
                    <li class="post">
                        <p><a href="{% url 'arch_blog:post' post.id %}">{{ post.title }}</a></p>
                        <div class="extract">{{ post.getAbstract }}</div>
                        <hr/>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No posts are available :(</p>
            {% endif %}
            </div>
        </div>
        <div class="tags">
        Tags:
        </div>
    </body>
</html>

mysite/arch_blog/templates/arch_blog/post.html
<center><h1>{{post.title}}</h1></center>
<p>{{post.body}}</p>
<h5>{{post.pub_date}}</h5>
{% if tags %}
    <p>
        {% for tag in tags %}
            <tag>#{{ tag }}</tag>
        {% endfor %}
    </p>
{% endif %}
<center><h4>Comments</h4></center>
{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
<form action="{% url 'arch_blog:comment' post.id %}" method="POST">
    {% csrf_token %}
    <textarea name="body" id="commnet_body">Put your comment here...</textarea><br>
    <input type="text" name="author" id="comment_author"/><br>
    <input type="submit" value="Comment"/>
</form>
{% if comments %}
    {% for comment in comments %}
    <p>{{ comment.body }}</p>
    <p><b>{{ comment.author }}</b>, <i>{{ comment.pub_date }}</i></p>
    {% endfor %}
{% else %}
    <p>No comments yet. Be the first! :)</p>
{% endif %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong> {{ error_message }} </strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% if question.choice_set.all %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>
{% else %}
    <p><strong>No possible answers found!</strong></p>
{% endif %}

mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }} </h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }} </li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>